# host_vars/p1.yaml
hostname: P1
loopback_name: Loopback0
iou: 2

domain_name: lab.local

mgmt:
  vrf: Mgmt-intf
  interface: Ethernet1/3
  ip: 10.1.1.2
  mask: 255.255.255.0
  gateway: 10.1.1.254

ospf:
  process_id: 1
  router_id: 2.2.2.2
  passive_interfaces:
    - Loopback0

interfaces:
  - name: Loopback0
    description: "Router ID"
    ip: 2.2.2.2
    mask: 255.255.255.255
    ospf:
      process: 1
      area: 0
  - name: Ethernet0/0
    description: "link to PE1"
    ip: 10.1.2.2
    mask: 255.255.255.0
    mpls: true
    ospf:
      process: 1
      area: 0
      network_type: point-to-point
      auth: true
  - name: Ethernet0/1
    description: "link to P2"
    ip: 10.2.3.2
    mask: 255.255.255.0
    mpls: true
    ospf:
      process: 1
      area: 0
      network_type: point-to-point
      auth: true
  - name: Ethernet0/2
    description: "link to RR1"
    ip: 10.2.5.2
    mask: 255.255.255.0
    mpls: true
    ospf:
      process: 1
      area: 0
      network_type: point-to-point
      auth: true

bgp:
  asn: 65
  router_id: 2.2.2.2
  vpnv4: false
  pe_ce: false

  peer_sessions:
    - name: rr-peers
      remote_as: 65
      update_source: Loopback0
      password: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                35303831313266663835646238353035346537356264663436646664616439646235653635613830
                6237646134653164343735363565336335366664613936610a386637616363613962306162623838
                37636235373832323538666332303465393965313338313230356537326234343533333439623862
                3465333435323734350a326666393930376336643833333733353565303863303065313232666661
                3761
      description: "RR Peers"

  peer_policies:
    - name: rr-peers-ipv4
      send_community: both
      next_hop_self: true
    - name: rr-peers-vpnv4
      send_community: both
      next_hop_self: true

  ibgp_peers:
    - ip: 5.5.5.5
      description: "RR1"
      peer_session: rr-peers
      peer_policy: rr-peers-ipv4
    - ip: 6.6.6.6
      description: "RR2"
      peer_session: rr-peers
      peer_policy: rr-peers-ipv4
